version: '3.7'
services:
  app:
    image: code.tritum.de:5555/senckenberg/agrifuture_desktop_agent:development
    environment:
      ADA_RUN_AGENT: 1
      ADA_RUNNING_CONTAINERS: 0
      ADA_HOST_DIRECTORY: "${PWD}/volumes/data"
      ADA_RUN_UUID: b051976e-182c-4ed3-80c6-e8ebdff91176
      # Select the pair you need to work with. You could also select one for
      # each language.
      ADA_PORTAL_DE: https://rapid-pipeline-portal.dev.local.dreistrom.land
      ADA_PORTAL_EN: https://rapid-pipeline-portal.dev.local.dreistrom.land/en
      # ADA_PORTAL_DE: https://dreistromland:4DuRyv2PGziZzoMQgJTm@agrifuture.senckenberg.de
      # ADA_PORTAL_EN: https://dreistromland:4DuRyv2PGziZzoMQgJTm@agrifuture.senckenberg.de/en
      ADA_CHECK_CERTIFICATES: 0
    ports:
      - '8041:80'
    volumes:
      - ./src/docker/buildfiles/opt/ada/app:/opt/ada/app
      - ./volumes/fakehome:/home/ada/.local/share/ada
      - ./volumes/data:/data:ro
    networks:
      - domainrouter

networks:
  domainrouter:
    external: true
