parameters:
  app_locales: [en, de]
twig:
  default_path: '%kernel.project_dir%/templates'
  globals:
    locales: '%app_locales%'

when@test:
  twig:
    strict_variables:
      trueservices:
    extension:
      intl:
        class: Twig_Extensions_Extension_Intl
        tags:
          - { name: twig.extension }
